### ISSUE TITLE
Cache preallocation in decoding

### ISSUE THREAD

**Issue by fxmarty** [fxmarty/accelerated-pytorch-transformers-generation#1]
# Motivation

We suspect [the concatenations of the key/value buffer](https://github.com/huggingface/transformers/blob/ba695c1efd55091e394eb59c90fb33ac3f9f0d41/src/transformers/models/gpt2/modeling_gpt2.py#L321-L322) at each generation step to be expensive.

FasterTransformer does preallocate the kv cache. Preallocating may also help `torch.compile`, also I don't quite get why (there are still dynamic shapes in the model itself, so why care about the model I/O?).

# Results

Some optimizations may still be missing. On commit 1acc7e4ea234d7143700234e51877acc9859f9ed

![image](https://github.com/fxmarty/transformers-preallocate-kv-cache/assets/9808326/19db7654-819d-4939-8306-e0b3e5691af5)
![image](https://github.com/fxmarty/transformers-preallocate-kv-cache/assets/9808326/0dd50f85-a3a0-4571-aa80-2a748b9c9942)
![image](https://github.com/fxmarty/transformers-preallocate-kv-cache/assets/9808326/3a1e6efb-2358-40f4-bf8e-d09261296fd5)
![image](https://github.com/fxmarty/transformers-preallocate-kv-cache/assets/9808326/adc4ec1c-529c-44b6-8e77-105b788e222a)
![image](https://github.com/fxmarty/transformers-preallocate-kv-cache/assets/9808326/e41bc4ca-1d3b-4625-9ec6-283b1442420b)
![image](https://github.com/fxmarty/transformers-preallocate-kv-cache/assets/9808326/48294201-9798-4083-9776-3ef4dbd6ca12)

# Todos
- [ ] `past_key_values` buffer should be initialized in the background, instead of requiring the user to initialize it himself and requiring to pass `generate(**inputs, past_key_values=past_key_values)`.
- [ ] Current implementation is likely to break with `accelerate` with naive pipeline parallelism, as the buffer is currently initialized on a single device
- [ ] Preallocated kv cache still does not help with small models / batch size.
- [ ] Support an iterative buffer, e.g. that auto-extends each 512 tokens, instead of initializing a buffer of size `max_new_tokens`. This may help reducing memory usage (and speed? probably not).
- [ ] Implement tests
- [ ] Should this be in optimum or transformers?
- [ ] Support all (is it possible?) decoding strategies, instead of currently only `greedy_search`
- [ ] Have it work with cross-attention
